### PR TITLE
split SmtMap into SMT Array and finite map

### PR DESCRIPTION
**Pull request by fdupress**
this is meant to enable the development of a library of infinite arrays (as SMT arrays from int)

This will break existing proofs. For most, the fix will be `s/SmtMap/FMap/`.

Creating as draft for now to gauge effect and effort on external CI.

### CODE REVIEW

**Comment by vbgl** [comment]
About Jasmin eclib, if I read the build log correctly, only `JModel_x86` fails and the issue should be trivially solved by https://github.com/jasmin-lang/jasmin/pull/884.

**Comment by fdupress** [comment]
Thanks @vbgl for looking into it. That does greatly simplify the synchronisation problem, since the fix seems to work independently of merging this PR.

Let me know if you want my review on that. Once it's merged, I'll flip this to ready and we get to work fixing the easy ones.

**Comment by vbgl** [comment]
Yes please. Your review there would ensure that someone looked at the changes before I merged them.

**Comment by fdupress** [comment]
Vincent, this is just to confirm here that I've re-run the CI job—I was hoping to be able to run more, but need to merge #606 first—and it's now unsurprisingly green. So we're good as expected on `eclib`.

**Comment by fdupress** [comment]
PR pending on SPHINCS+, PR stuck behind another PR on XMSS (both proofs). Once merged, this is good to go.

**Comment by fdupress** [comment]
🎉 ready for review and mergin, @strub.

As a side-effect of this effort, we now have gitlab and github (thanks, @MM45) CI setups that are somewhat generic, and can be used for the local CI of external proofs that aim at keeping up with `main`.

We'll put some spare effort into moving them somewhere easy to find when we have effort to spare.

**Review by strub — APPROVED** [review]

**Pull request merged**
