### PR TITLE
Remove superfluous renamings in BitWord.eca #146

### PR DESCRIPTION
**Pull request by alleystoughton**

### CODE REVIEW

**Review by bgregoir — COMMENTED** [review]
What is the purpose of removing the rename ?
I think that the use of rename can be a bad idea because the cloned theory can not be seen as an instance of the original one. But the removing it rename can break other developments.

**Comment by strub** [comment]
> What is the purpose of removing the rename ?

@bgregoir Have a look at #146

**Review by strub — COMMENTED** [review]
Squash your PR in a single commit & link your commit to the issue it is related to. See:

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by bgregoir** [comment]
So this is perfect, apparently I need to wake-up this morning

**Review by strub — CHANGES_REQUESTED** [review]
See my previous comment.

**Comment by bgregoir** [comment]
I did it, this is why I say : "this is perfect"

**Comment by alleystoughton** [comment]
There are advantages to being in a later time zone ;-)

**Review by strub — APPROVED** [review]

**Pull request merged**
