### PR TITLE
Added formosa-25519 curve25519 to external CI

### PR DESCRIPTION
**Pull request by JoaoDiogoDuarte**
Added formosa-25519's Curve25519 proof to the external CI.

Draft as the changes necessary to the formosa-25519' such that it can the proofs can be checked by the CI. There is a PR for this https://github.com/formosa-crypto/formosa-25519/pull/25.

### CODE REVIEW

**Comment by strub** [comment]
> Unfortunately for us, the same error message is output if it's the scenario file that can't be found, so I'll be digging a bit into what is causing this, hopefully giving you an update soon.

Hug. That's pretty bad

**Comment by fdupress** [comment]
See the PR I created in the meantime. Probably not the cleanest fix.

**Comment by JoaoDiogoDuarte** [comment]
Strange, running `easycrypt runtest ../../tests.config curve25519` in my local machine works. Does the `tests.config` have to be in the same directory that we run `runtest`?

**Comment by fdupress** [comment]
This is why I'm trying to get some diagnostics out of runtest, here (with #643): I don't know where it's looking.

The CI job is using the "subdir" from the job config as working directory for the run. So in theory, the path should be relative to that. But if that was the case, this job shouldn't fail...

**Comment by fdupress** [comment]
Oh, yes it should: your config file in the repo is in the subdir, not two levels up from it.

Fix the subdir string.

**Comment by JoaoDiogoDuarte** [comment]
> Oh, yes it should: your config file in the repo is in the subdir, not two levels up from it.
> 
> Fix the subdir string.



> Oh, yes it should: your config file in the repo is in the subdir, not two levels up from it.
> 
> Fix the subdir string.

Fixed, my bad. Let's see if it works.

**Comment by JoaoDiogoDuarte** [comment]
Ok, so it can't find the Jasmin eclib - not sure how to deal with that. Furthermore, is this extracting the Jasmin implementation before running the `runtest`?

**Comment by fdupress** [comment]
> Ok, so it can't find the Jasmin eclib - not sure how to deal with that. Furthermore, is this extracting the Jasmin implementation before running the `runtest`?

Finding `eclib`: we should do a recursive clone.

Extracting Jasmin implementation: no, by design, the only thing the external CI will do is run `easycrypt runtest` over a particular configuration. We do not have the capacity to set things up so this runs externally to the EasyCrypt CI, and we do not have the capacity to monitor changes to external setups for iffy scripts that we'd then run within our castle. We had already discussed this in the broader context of libjade—having the libjade CI produce an artefact containing just the files that should be checked by EasyCrypt's CI (including basic config).

**Pull request closed without merging**
