### PR TITLE
First pass: slices are inclusive

### PR DESCRIPTION
**Pull request by fdupress**
Make formula slices inclusive.

This doesn't completely solve the problem as slices with negative indices still don't make sense.

### CODE REVIEW

**Comment by chdoc** [comment]
> This doesn't completely solve the problem as slices with negative indices still don't make sense.

What's the intended meaning of negative indices?

**Comment by fdupress** [comment]
> > This doesn't completely solve the problem as slices with negative indices still don't make sense.
> 
> What's the intended meaning of negative indices?

They count from the end; this is more stable in post-conditions, for example.

But because are indices are 1-based, I can't figure out what makes sense: should `[-3:-1]` select 1, 2 and 3, or 2, 3 and 4 out of `[1; 2; 3; 4]`? The old behaviour selected 1, 2 and 3 (and there was no way of selecting the final element in a slice, as with positive indices); the current behaviour (with the patch) selects the last 3 elements, which feels wonky—I would not expect `-1` to select the last element. (And no, I don't think we should parse `-0` differently from `0` just for this.)

**Comment by strub** [comment]
I find the new behaviour pretty convincing. We agree that `0` is an invalid index?

**Comment by fdupress** [comment]
> I find the new behaviour pretty convincing.

I don't know why, but it bothers me. I realise it's literally keeping the meaning of `-` as "index in the reserved list", but making it 1-based and consistent with the positive indices, but it just _feels_ icky. We can probably ignore my feelings: I'll get over it.

> We agree that `0` is an invalid index?

Yes, it remains an invalid index.

**Comment by strub** [comment]
Ok, so for me, we're ready to merge.

**Comment by chdoc** [comment]
I agree with @fdupress , interpreting `#[:-1]pre` as the full list and `#[:-2]pre` as chopping off one conjunct at the right feels _weird_, probably because "minus" has the connotation or removing stuff, and `-1` is "all the way to the end". But it's consistent and easy enough to explain, so maybe we should just keep it. I'm not sure :thinking:

**Comment by strub** [comment]
This is this or accepting `-0` as an index. Not sure it's better.

**Comment by fdupress** [comment]
> This is this or accepting -0 as an index. Not sure it's better.

Well, `-0` parses as `0` at the moment, so we could always make `0` a valid index (with the completely non-sensical meaning of "the last element in the list), and just happen to write it `-0` when we use it. I hate it. I hate it a lot more than just forbidding slices with negative indices, which I hate just a tiny bit more than the slices we have now. (In this branch.)

I vote we merge, and revisit when someone:
1) actually wants to use slices with negative indices, and
2) comes up with a better solution.

**Comment by strub** [comment]
Fine with me.

**Pull request merged**
