### PR TITLE
Improve parser for anonymous proc parameters

### LINKED ISSUE #108: Parse error when using underscores for parameter names in module type procedure with at least 2 parameters.
When defining the following module type, EC gives a parse error (which moves the cursor to the comma in between the two parameters of proc):
```
module type OR = {
  proc init(_: int, _: bool) : unit
}.
```
Changing one of the underscores to a proper parameter name still gives the same error. Using underscore when the procedure only has a single parameter works properly.

### PR DESCRIPTION
**Pull request by fdupress**
(Partially) Resolves #108.

This doesn't allow partially anonymous parameter lists.

### CODE REVIEW

**Review by strub — CHANGES_REQUESTED** [review]
I would prefer that we homogenise the parser here by allowing a mixture of `_` and named parameters and to reject mixture at typing time. (We have far too many over-specified parsing rules)

**Comment by fdupress** [comment]
I've now rebased on `main` and simplified the parser to push the checks into typing.
It turns out that with the current handling of procedures, there is no need for checks: we can simply create fresh names for anonymous parameters and type as normal.

I've only carried out limited tests, so we might want to keep this tagged as experimental for a while.

**Comment by fdupress** [comment]
Oh, also, my code style is crap. Please make suggestions.

One I have is that we should factor out the code that processes the parameter list so it's not repeated between module signature typing and module typing.

**Comment by fdupress** [comment]
I have now, and it looks fine.

```
module type T = {
  proc f(_ : int, x : real): bool
}.

print T.
```

yields

```
module type T  = {
  proc f(_ : int, x : real) : bool 
}
```

```module M = {
  proc f(_ : int, x : real): bool = {
    return true;
  }

  proc g(_ : int, x): real = {
    return x;
  }
}.

print M.
```

yields

```
module M = {
  proc f(_ : int, x : real) : bool = {
    return true;
  }
  
  proc g(_ : int, x : real) : real = {
    return x;
  }
}.
```

**Comment by fdupress** [comment]
> I would like to known what does the pretyprinter for function with more than 1 _. proc f (_:int, _: int). It is also interesting to known what's happen with proj arg as you notice

So I tried `proc f (_ : int, _ : int)` and it just prints it as is.

In a goal on a concrete procedure with anonymous arguments, `arg` expands nicely and as expected. This is slightly confusing when there are several anonymous arguments (because all of them are `_`). I think this is one of the corner cases, but it's worth keeping in mind that the anonymous arguments cannot be *used* in code (not even as a projection of `arg`), so it's unlikely we'd ever actually want to refer to them.

**Comment by fdupress** [comment]
More concretely, the proof goal after

```
module M = {
  proc f(_ : int, _ : real): bool = {
    return true;
  }

  proc g(_ : int, x): real = {
    return x;
  }
}.

equiv Mf_Mf_arg: M.f ~ M.f: ={arg} ==> ={res}.
proof.
proc=> /=.
```

is

```
Current goal

Type variables: <none>

------------------------------------------------------------------------------------------------------------------
&1 (left ) : {_ : int, _ : real} [programs are in sync]
&2 (right) : {_ : int, _ : real}

pre = ={_, _}


post = true
```

This seems reasonable.

**Comment by bgregoir** [comment]
I am not sure of the last point, as you said arg.`1 and arg.`2 will be printed _.
I think we should modify the memenv to take into account the fact that now 
some proj of arg can be _ and the printing should not use the short cut.

**Comment by fdupress** [comment]
I'm happy to prevent the declaration of anonymous args for concrete procedures, but it felt like something nice to have for simulation-based stuff. In this case, and with `_` as a valid argument names that can't be referred to in the body of the procedure, you can have a single interface for the real procedure that takes the secret as argument and the ideal procedure that doesn't, and easily convince a reader that the simulator doesn't use the secret (because it's named `_`).

I need to think and try some things around contracts for abstract procedures and seeing how they're printed. It's possible that stopping the use of `_` in concrete procedures solves all issues: we never have a `memenv` for abstract procedures, and printing of contracts preserves `arg` and its projections.

**Comment by strub** [comment]
> I am not sure of the last point, as you said arg.`1 and arg.`2 will be printed _. I think we should modify the memenv to take into account the fact that now some proj of arg can be _ and the printing should not use the short cut.

I think it would be better to change the internal representation for named arguments from `variable list option` to `variable option list`. Of course, we could hack the pretty-printer to check whether the argument name is `_` and has not been given, but this is hackish w.r.t. having an option type.

**Comment by fdupress** [comment]
This is now ready for re-re-review. The memory handling needs a thorough cleanup, but this is doing the work.

Concrete procedures no longer support anonymous arguments, but everything else, at least as exercised in the standard lib and examples, works. There is probably some factoring out to do (there are a few places that turn a potentially anonymous variable that we know is named into a named variable, for example), but I'd prefer to do it once we know this is the solution we want.

**Comment by fdupress** [comment]
Less integrated testing results from overnight runs:
- The PRG tutorial works.
- The SHA3 algorithmic security proofs work.
- The XSalsa20/cascades algorithmic security proofs work.
- A number of other (small) proofs I've kept up-to-date also work.

Functionally, this seems to be transparent. (Modulo, apparently, the fact that it modifies one bit of behaviour enough that we need to nudge `smt` with a `crush` in one instance in the ChaCha+Poly proof.)

**Review by strub — APPROVED** [review]

**Pull request merged**
