### PR TITLE
Remove the "nosmt" mechanism

### PR DESCRIPTION
**Pull request by strub**

### CODE REVIEW

**Comment by alleystoughton** [comment]
Is there a new mechanism that replaces this? I was the one that implemented nosmt for operators. It's crucial for some of my work.

**Comment by strub** [comment]
The `nosmt` keyword is going to disappear. This is pure technical debt, it has a lot of ad-hoc variations that have been introduced for specific projets & it has not been used consistently for the last 10 years.

IMO, this is orthogonal to having opaque operators to SMT (but even here, the implementation was intricated).

**Comment by alleystoughton** [comment]
With lemmas and axioms, one can select whether to use them in smt(...). But with concrete operators, this is not possible. Making [opaque] also apply to smt would be one solution. For my needs that would be perfect.

**Comment by strub** [comment]
Discussion is now in #576

**Review by fdupress — APPROVED** [review]

**Pull request merged**
