### PR TITLE
Please generate an AppImage and upload it to GitHub Releases

### PR DESCRIPTION
**Pull request by probonopd**
Also, please enable GitHub Issues so that one can contribute without having to send pull requests like this one.

Thanks.

### CODE REVIEW

**Comment by strub** [comment]
We have a tracker on easycrypt.info. I am planing to move the tracker to github but as long as this migration is not done, I am not going to move to a situation where we have two trackers.

**Comment by strub** [comment]
Answering your PR: the last time I used it, I have not been convinced by AppImage. So you are free to make a PR to add some support for generating an AppImage image (and i will happily merge it) but i’m not going to do it on my time.

**Comment by probonopd** [comment]
> I am planing to move the tracker to github

That's great. Makes it much easier for first-time, "drive-by" contributors. Thank you!

**Comment by probonopd** [comment]
> the last time I used it, I have not been convinced by AppImage

Why? I'm genuinely interested in your honest feedback. Thank you.

**Pull request closed without merging**
