### PR TITLE
pretty printer: better handling of long module paths

### PR DESCRIPTION
**Pull request by strub**

### CODE REVIEW

**Comment by oskgo** [comment]
This is an improvement, but it doesn't handle nested module parameters. Consider the following example:
```
module type Foo = {}.
module VeeeeeeeeeeeeeeeryLongName1 = {}.
module VeeeeeeeeeeeeeeeryLongName2 (F: Foo): Foo = {}.
module VeeeeeeeeeeeeeeeryLongName3 (F: Foo) = {
  proc main() = {}
}.
module VeeeeeeeeeeeeeeeryLongName4 (F: Foo) = {
  proc main() = {}
}.

equiv test: VeeeeeeeeeeeeeeeryLongName3(
              VeeeeeeeeeeeeeeeryLongName2(
              VeeeeeeeeeeeeeeeryLongName1
)).main
          ~ VeeeeeeeeeeeeeeeryLongName4(
              VeeeeeeeeeeeeeeeryLongName1).main
           : true ==> true.
proc*.
```

**Comment by strub** [comment]
@oskgo This should now work.

**Comment by oskgo** [comment]
Indeed it does. My original development is now nice and slim. I think it might be a bit too liberal with the newlines now though:
```
module type Foo = {}.
module Na1 = {}.
module M (F: Foo): Foo = {}.
module N (F: Foo) = {
  proc p() = {}
}.

equiv test: N(M(Na1)).p
          ~ N(Na1).p
           : true ==> true.
proc*.
(*
------------------------------------------------------------------------
&1 (left ) : {r : unit}
&2 (right) : {r : unit}

pre = true

r <@                       (1)  r <@                     
  N(                       ( )    N(Na1).p()             
    M(                     ( )                           
     Na1)).p()             ( )                           

post = true
*)
```

**Comment by strub** [comment]
Here, it seems that your printing width is very narrow. With a width of 80, this is what I get:

```
Current goal

Type variables: <none>

--------------------------------------------------------------------------
&1 (left ) : {r : unit}
&2 (right) : {r : unit}

pre = true

r <@ N(M(Na1)).p()         (1)  r <@ N(Na1).p()          

post = true
```

**Comment by strub** [comment]
Ok. I think that the default printing width is too narrow. I  just opened #598

**Comment by oskgo** [comment]
Makes sense. I was assuming that the horizontal bar above the memories would be constrained to be less wide than the limit.

**Comment by strub** [comment]
> Makes sense. I was assuming that the horizontal bar above the memories would be constrained to be less wide than the printing width.

Oh, good remark!

**Pull request merged**
