### PR TITLE
user reduction: fix some incompleteness issues

### LINKED ISSUE #319: hint simplify [reduce] issue involving record field selection
Here is an example where `hint simplify [reduce]` doesn't work as expected. It seems to have something to do with the equation to be rewritten involving record field selection:

```
require import AllCore.

type ('a, 'b) epdp = {enc: 'a -> 'b; dec : 'b -> 'a option}.

op nosmt valid_epdp (epdp : ('a, 'b) epdp) : bool =
  (forall (x : 'a), epdp.`dec (epdp.`enc x) = Some x) /\
  (forall (y : 'b, x : 'a), epdp.`dec y = Some x => epdp.`enc x = y).

lemma epdp_enc_dec (epdp : ('a, 'b) epdp, x : 'a) :
  valid_epdp epdp => epdp.`dec (epdp.`enc x) = Some x.
proof.
rewrite /valid_epdp => [[enc_dec _]].
by rewrite enc_dec.
qed.

type s, t.

op epdp_s_t : (s, t) epdp.

axiom valid_epdp_s_t : valid_epdp epdp_s_t.

hint simplify [reduce] epdp_enc_dec.
hint simplify valid_epdp_s_t.

(* for testing simplification: *)

op P : s option -> bool.

lemma foo2 (x : s) :
  P (epdp_s_t.`dec (epdp_s_t.`enc x)).
proof.
rewrite epdp_enc_dec //.
(*
worked!

Current goal

Type variables: <none>

x: s
------------------------------------------------------------------------
P (Some x)
*)
abort.

lemma foo3 (x : s) :
  P (epdp_s_t.`dec (epdp_s_t.`enc x)).
proof.
simplify.
(* does nothing - should it work? *)
```

For comparison, here is the same example where encoding and then decoding is turned into an operator. Here simplification works as expected.

```
require import AllCore.

type ('a, 'b) epdp = {enc: 'a -> 'b; dec : 'b -> 'a option}.

op nosmt valid_epdp (epdp : ('a, 'b) epdp) : bool =
  (forall (x : 'a), epdp.`dec (epdp.`enc x) = Some x) /\
  (forall (y : 'b, x : 'a), epdp.`dec y = Some x => epdp.`enc x = y).

op f (epdp : ('a, 'b) epdp, x : 'a) : 'a option =
  epdp.`dec (epdp.`enc x).

lemma epdp_enc_dec (epdp : ('a, 'b) epdp, x : 'a) :
  valid_epdp epdp => f epdp x = Some x.
proof.
rewrite /valid_epdp => [[enc_dec _]].
by rewrite /f enc_dec.
qed.

type s, t.

op epdp_s_t : (s, t) epdp.

axiom valid_epdp_s_t : valid_epdp epdp_s_t.

hint simplify [reduce] epdp_enc_dec.
hint simplify valid_epdp_s_t.

(* for testing simplification: *)

op P : s option -> bool.

lemma foo3 (x : s) :
  P (f epdp_s_t x).
proof.
simplify.
(*
works!

Current goal

Type variables: <none>

x: s
------------------------------------------------------------------------
P (Some x)
*)
```

### PR DESCRIPTION
**Pull request by strub**
Record projectors being operators, they are subject to user defined rules.

Fix #319

### CODE REVIEW

**Comment by alleystoughton** [comment]
This works for me! You have two unused variable warnings in `ecCallbyValue.ml`, so I'm not going to approve it, as auto-merge is turned on, assuming you'd like to fix this first.

**Comment by strub** [comment]
Indeed. Fixed.

**Comment by strub** [comment]
The CI should compile with warnings-as-errors.

**Review by alleystoughton — APPROVED** [review]
Thanks for this change!

**Pull request merged**
