### PR TITLE
[build] Add basic dune support

### PR DESCRIPTION
**Pull request by ejgallego**
Add experimental support for buidling `ec` using dune. Use

```
dune build
```

We don't add support for building the stdlib yet. Some fixes are needed, for example to get commit information Dune provides nice facilities, but that'd mean the make system has to go first.

I've also fixed a few warnings that are set by default, IMO these make sense to be enabled but commits could be dropped as necessary.

### CODE REVIEW

**Comment by ejgallego** [comment]
Timings:
```
$ OCAMLBUILD_JOBS=8 /usr/bin/time -v make -j 8

  Command being timed: "make -j 8"
  User time (seconds): 19.43
  System time (seconds): 4.74
  Percent of CPU this job got: 121%
  Elapsed (wall clock) time (h:mm:ss or m:ss): 0:19.82

$ /usr/bin/time -v dune build

  Command being timed: "dune build"
  User time (seconds): 26.73
  System time (seconds): 5.21
  Percent of CPU this job got: 307%
  Elapsed (wall clock) time (h:mm:ss or m:ss): 0:10.40

$ /usr/bin/time -v dune build @check

  Command being timed: "dune build @check"
  User time (seconds): 18.07
  System time (seconds): 3.95
  Percent of CPU this job got: 281%
  Elapsed (wall clock) time (h:mm:ss or m:ss): 0:07.82
```

**Comment by strub** [comment]
I am sorry, but I don't understand why changing the build system should impact nearly 50 ocaml files.

**Comment by ejgallego** [comment]
It is explained in the PR comment, as well as in the commit log itself. The set of commits are incremental, first commit does port the build system to dune, the rest each of them fix OCaml warnings in order to reduce the delta to the default build configuration.

**Comment by strub** [comment]
Yes, but it would have been simpler to move to dune without changing the set of warnings. Let's try to split this because there are warnings that I don't want to see and the integration of dune is only partly done here.

**Comment by strub** [comment]
BTW, currently taking the lock

**Comment by ejgallego** [comment]
Indeed it would have made sense to submit two PRs. I can do the split but I guess you will be done with this soon :)

**Comment by ejgallego** [comment]
> it would have been simpler to move to dune without changing the set of warnings

Just take the first commit, it should do exactly that.

**Comment by strub** [comment]
Thanks for the PR & sorry for the delay!

**Comment by ejgallego** [comment]
> Thanks for the PR & sorry for the delay!

Pas de problème ! Pour gérer les fichiers .ec, qu'on fais en Coq est générer un fichier `dune` (avec `(subdir ...)`) comment pas bootstrap, c'est très utile pour les test incrémentaux.

On espère que Dune 3.0 aura:
```
(rule
  (target ec_rules.sexp)
  (deps (source_tree .))
  (action (run ./gen_ec_rules.exe)))

(include ec_rules.sexp)
```
donc le pas bootstrap déviant pas nécessaire.

**Pull request merged**
