### PR TITLE
[internal] Fix glob unsoundness

### LINKED ISSUE #102: Unsoundness of glob
I [Dominique Unruh] (together with Denis Firsov) have discovered an unsoundness in the module system of EasyCrypt (false is provable).

The basic problem is the following: When B, A are concrete modules, glob B(A) is computed to contain only those variables that are actually reachable by procedures in B. When B, A are abstract modules, glob B(A) = (glob B, glob A). So if we reason about glob B(A) in a situation where B,A are abstract, and then instantiate B,A with concrete modules, the result of that reasoning will not be valid anymore.

The following theory proves `false`:

```
module type AT = {
  proc p():unit
}.

module A : AT = {
  var x : int
  proc p() = {}
}.

(* glob A = A.x : int *)

module type BT(A:AT) = {
  proc p():unit
}.

module B(A:AT) = {
  proc p() = {}
}.

(* glob B(A) = {} : unit, no matter what A is because B does not invoke A *)

(* Auxiliary lemma, nothing fishy here *)
lemma singleton_unit: (forall (x y:unit), x=y) <=> true.
  rewrite /singleton.
  progress.
qed.
    
(* Auxiliary lemma, nothing fishy here *)
lemma singleton_int: (forall (x y:int), x=y) <=> false.
  rewrite /singleton.
  simplify.
  rewrite negb_forall.
  exists 0.
  simplify.
  rewrite negb_forall.
  exists 1.
  trivial.
qed.

(* Auxiliary lemma, nothing fishy here *)
lemma singleton_pair ['a 'b]: (forall (x y:'a*'b), x=y) <=> ((forall (x y:'a), x=y) /\ (forall (x y:'b), x=y)).
  rewrite /singleton.
  apply iffI.
  move => H.  
  split.
  (* Goal 1 *)
  move => x y.  
  have H1 := H (x,witness) (y,witness).
  smt.
  (* Goal 2 *)
  move => x y.  
  have H1 := H (witness,x) (witness,y).
  smt.
  (* Goal 2 *)
  move => [H1 H2] x y.
  have H1' := H1 x.`1 y.`1.
  have H2' := H2 x.`2 y.`2.
  smt.
qed.

(* The trouble starts here *)
lemma contradiction: false.
  have H1: exists (B0<:BT) (A0<:AT), (forall (x y:glob B0(A0)), x=y) /\ ! (forall (x y:glob A0), x=y).
    exists B A.
    (* B0,A0 changed to B,A. We have glob B(A) = unit and glob A = int. *)
    rewrite singleton_unit singleton_int.
    trivial.
  elim H1 => B0 A0 [H2 H3].
  have H4: !(forall (x y:glob B0(A0)), x=y).
    (* We have glob B0(A0) = glob B0 * glob A0, thus H4 follows from H3 *)
    rewrite singleton_pair.
    smt.
  (* H2,H4 are a contradiction *)
  smt.
qed.
```

### PR DESCRIPTION
**Pull request by Cameron-Low**
This fixes #102 through eager normalization of module globs at typing and instantiation time.

### CODE REVIEW

**Review by bgregoir — COMMENTED** [review]
Hi Cameron, 
  I have not read the full code but I think the reference f_norm_mod is not reasonable. 
  I think the good way to do it, is that in EcCoreFol, adding a module in the substitution should
  have this type 
    f_bind_mod : f_subst -> EcIdent.t -> EcPath.mpath * (EcIdent -> form) (* memory to global formula *) -> f_subst     
  instead of 
    f_bind_mod : f_subst -> EcIdent.t -> EcPath.mpath -> f_subst
  Then in EcFol, you can add a f_bind_mod that is parametrized by an env allowing to
  compute the form of the global.
   I have used (EcIdent -> form) but it can be any data structure allowing to build the formula once you have the memory, for example the type "use" defined in EcEnv.ml (which can be move).

   But this global reference is for sur a big source of bug.

**Comment by Cameron-Low** [comment]
No worries, I've fixed that following your suggestion.

**Comment by strub** [comment]
@bgregoir With Cameron's fix to your comment, are you happy to go? For me, the PR is ok.

**Review by strub — APPROVED** [review]

**Review by bgregoir — APPROVED** [review]
Thank a lot for all of this.
Have we try to check is the bug is still present?
Our hope is not but just to be sure....

**Comment by fdupress** [comment]
I'll run a check on SHA3.

Beyond that, I think someone will need to put some work on #399 to split off the external checks so it can be run only on PRs without losing dependencies on build jobs (so cachix has a chance to do its work instead of getting slammed with parallel builds). It unfortunately cannot be me right now.

**Comment by alleystoughton** [comment]
I tried this on all my developments, and everything works. :-)

**Pull request merged**
