### PR TITLE
[External CI] Add XMSS and SPHINCS+

### PR DESCRIPTION
**Pull request by MM45**

### CODE REVIEW

**Comment by strub** [comment]
Is `-jobs 1` really necessary?

**Comment by MM45** [comment]
So for SPHINCS+, I remember stuff not checking with more than 1 job (back when we created the artifact for submission). For XMSS, I didn't explicitly check this, I simply copied from SPHINCS+.

**Comment by fdupress** [comment]
Just a note that in both cases (in SPHINCS+, and therefore also in XMSS, whose  config was adapted from it), the local CI script itself hard codes a single job.

If we want to remove the constraint here, we should first remove it there and check if anything breaks.

**Review by strub — APPROVED** [review]

**Comment by strub** [comment]
I removed the `-jobs 1`

**Comment by fdupress** [comment]
And the CI checks run successfully with 4 parallel jobs. I think it's good to go, @MM45. (And we can remove the hardcoded job limit in the local CIs as well.)

**Comment by MM45** [comment]
For local CI, I removed the `-jobs 1` option in the `easycrypt runtest` commands, but it is still running with only 1 job. Is this expected, or should I remove something else as well (looking at, e.g., the `ECRJOBS: 1` under `env:`)?

**Pull request merged**
