### PR TITLE
default.nix: option to install provers

### PR DESCRIPTION
**Pull request by strub**

### CODE REVIEW

**Comment by vbgl** [comment]
You wight be interested in the `withProvers` attribute of the `why3` package: it is meant to bring `why3` preconfigured with provers.

**Comment by strub** [comment]
The option seems to create a Why3 configuration file in a non-standard location that is used by a wrapper around the Why3 binary. This won't work for EasyCrypt that 1. use the API, 2. use also a non-standard location for it's Why3 configuration file :/

**Comment by strub** [comment]
Hou, I am wrong: EC reads the file from the standard location if it cannot a Why3 configuration file in the EC configuration directory. So this could work if the nix recipe installs the Why3 configuration in the home directory.

**Review by ethanlee515 — APPROVED** [review]

**Comment by chdoc** [comment]
Does the configuration still work if one calls `easycrypt why3config`?

**Comment by strub** [comment]
> Does the configuration still work if one calls `easycrypt why3config`?

What do you mean?

**Comment by strub** [comment]
> Does the configuration still work if one calls `easycrypt why3config`?

I do not use `why3.withProvers` in this PR. This is something we might want to use in a follow-up PR.

**Pull request merged**
