### PR TITLE
Take PolyReduce theory from Kyber project

### PR DESCRIPTION
**Pull request by ethanlee515**
Add choice-based inverses and fix broken proofs from subtype changes

### CODE REVIEW

**Comment by strub** [comment]
Do you know who is the initial author of this file?

**Comment by fdupress** [comment]
>  The theory was originally created by @Pierre-Yves Strub iirc and I only made some changes, so it wouldn't be right if I made the commit without attributing it to him.

https://formosa-crypto.zulipchat.com/#narrow/stream/308381-EasyCrypt.3A-questions-.26-features/topic/.60PolyReduce.60.20for.20the.20stdlib/near/365116516

If it wasn't you, we're going to need to do some digging... Was it from @oskgo?

**Comment by ethanlee515** [comment]
I thought @strub you said you wrote it...? Maybe I'm really missing something.

> I am the author of PolyReduce

from https://formosa-crypto.zulipchat.com/#narrow/stream/322819-Projects.3ADilithium/topic/Packaging.20EC.20dev/near/328998359

**Comment by oskgo** [comment]
I didn't write it. I thought @MM45 wrote it for Saber, but maybe he got it from somewhere else as well.

**Comment by strub** [comment]
I a getting old :)

**Comment by chdoc** [comment]
Some of the lemmas (e.g. `polyLXE coeffs` and the last three lemmas) have proofs that could be made more idiomatic/compact.

**Comment by strub** [comment]
> Some of the lemmas (e.g. `polyLXE coeffs` and the last three lemmas) have proofs that could be made more idiomatic/compact.

I am planning to do a full pass on the file before merging.

**Comment by chdoc** [comment]
Looks good! Thanks.

**Pull request merged**
