### PR TITLE
[theories] FunRO: RO for FinType using dfun for init

### PR DESCRIPTION
**Pull request by chdoc**
as discussed [on Zulip](https://formosa-crypto.zulipchat.com/#narrow/stream/308381-EasyCrypt.3A-questions-.26-features/topic/FunRO) 

Invariant inspired by  `init_eager` on `deploy-qrom-update:T_QROM`  (basically the same for `ROM`)

### CODE REVIEW

**Comment by chdoc** [comment]
CI finally went through :tada:

**Comment by fdupress** [comment]
It was the "just hit it with a hammer right... here" fix.

I'll hold off merging until Monday, just to avoid the risks associated with merging then walking off for the weekend.

**Comment by chdoc** [comment]
> I'll hold off merging until Monday, just to avoid the risks associated with merging then walking off for the weekend.

No problem, the person asking for this is not going to need this on the weekend. :+1:

**Comment by chdoc** [comment]
@fdupress Even Monday AoE is drawing to a close ^^

**Pull request merged**
