### PR TITLE
port Dexcepted to dresrict and deprecate Dfilter

### LINKED ISSUE #233: Merge `drestrict` & `dfilter`.
Currently, the standard library contains two related operators on distributions: `drestrict p d` (that filters `d`, keeping the events that validate `p`) and `dfilter p d` (that filters `d`, removing the events that validate `p`). Note that `dfilter` uses a naming convention that is against the one used for `List.filter` and `FSet.filter`.

Given that there is a direct relation between `drestrict` & `dfilter`, it is questionnable to have these two operators.

We might want to merge these two definitions.

### PR DESCRIPTION
**Pull request by chdoc**
fixes #233

### CODE REVIEW

**Comment by strub** [comment]
Shall we try to fix #236 first so that this PR can use the deprecation mechanism? (Yeah, I know that I added the issue #236 after your PR  😄 )

**Comment by chdoc** [comment]
> Shall we try to fix #236 first so that this PR can use the deprecation mechanism? (Yeah, I know that I added the issue #236 after your PR smile )

Fine with me, I don't think this is urgent.

**Comment by strub** [comment]
We should not wait for the deprecation mechanism to be there. Could you rebase this PR? I'll then merge it.

**Comment by chdoc** [comment]
> We should not wait for the deprecation mechanism to be there. Could you rebase this PR? I'll then merge it.

Done!

**Review by strub — APPROVED** [review]

**Pull request merged**
