### PR TITLE
[stdlib]: remove axioms (int + inductive schemes)

### PR DESCRIPTION
**Pull request by strub**

### CODE REVIEW

**Review by fdupress — APPROVED** [review]
Are "axiomatized by" operators marked as lemmas? Are there more than just `List.sort` that should be made `opaque` instead?

All good if these are all done, or intended as a future pass.

**Comment by strub** [comment]
Well, axioms from "axiomatiazed by" should not be marked as axioms anyway. I can do the change now.

**Comment by strub** [comment]
> Well, axioms from "axiomatiazed by" should not be marked as axioms anyway. I can do the change now.

Done.

**Comment by strub** [comment]
The last source of axioms comes from the AlgTactic theory. This one will be trickier to solver.

**Review by fdupress — APPROVED** [review]

**Pull request merged**
