### PR TITLE
New tactic to alias a subexpression of an instruction

### PR DESCRIPTION
**Pull request by strub**

### CODE REVIEW

**Comment by fdupress** [comment]
This looks useful. The implementation seems to use a different meant to the codepos parameter than the standard `alias`.

The standard `alias` takes a line number to insert a new line at. This variant uses the line number to match an expression in.

Perhaps a syntax like `alias codepos vname := pattern at codepos` would allow both selecting the line where the new variable initialisation is inserted (consistently with `alias`) and the line in which to match?

**Comment by strub** [comment]
What you propose is harder because you have to verify that there is no modification of the program variables of the aliases expression. Your variant could be done outside of the TCB as `alias` + `move`.

**Comment by fdupress** [comment]
Sure, but my comment was more on the inconsistent interpretation of the same tactic prefix between two variants. I'm happy if the new tactic is `alias var := pattern at/in codepos.`

**Comment by strub** [comment]
I updated the syntax

**Review by fdupress — APPROVED** [review]

**Pull request merged**
