### PR TITLE
Fix bug in theory replay for modules.

### LINKED ISSUE #292: "module is incompatible" error with iterated theory clones
I would have expected the following to work, but I get anther "module is incompatible" error.
```
(* abstract theories *)

abstract theory AT0.
type a,b.
const c : b.

module M = { 
  proc f (x:a) : b = { return c; }
}.
end AT0.

abstract theory AT1.
  clone import AT0 as T0.
end AT1.

abstract theory AT2.
  clone import AT1 as T1. 
end AT2.

(* instances *)

clone AT0 as MyT0 with 
  type a <= int,
  type b <= int,
  op c <= 0.

clone import AT1 as MyT1
  with theory T0 <= MyT0.

clone AT2 as MyA2 with 
  theory T1 <- MyT1.
(* fails with: module `T1.T0.M` is incompatible *)
```

### PR DESCRIPTION
**Pull request by strub**
When checking for module convertibility, check the computed module flat expression (i.e. all module aliases have been resolved), not the module expression.

Fix #292

### CODE REVIEW

**Comment by chdoc** [comment]
My minimal example now works, but the actual code I was working on now triggers:
```
anomaly: File "src/ecEnv.ml", line 1598, characters 13-19: Assertion failed
```
I don't have a minimal example yet, but the good news is that this time I'm sure this is a bug. :smiley:

**Comment by strub** [comment]
I assume that your example implies functors. The fix will have to be a little be more subtil.

**Comment by chdoc** [comment]
You're right. My example did involve functors. Here is another small example that doesn't work:
```
(* abstract theories *)

abstract theory AT0.
type a,b.
const c : b.

module type OT = { proc o (x : a) : b }.

module type AT (O : OT) = { 
  proc guess () : bool
}.

module O : OT = { 
  proc o (x:a) : b = { return c; }
}.

module M(A : AT) = { 
  proc main() = { 
    A(O).guess();
  }
}.

end AT0.

abstract theory AT1.
  clone import AT0 as T0.
end AT1.

abstract theory AT2.
  clone import AT1 as T1. 
end AT2.

(* instances *)

clone AT0 as MyT0 with 
  type a <= int,
  type b <= int,
  op c <= 0.

clone import AT1 as MyT1
  with theory T0 <= MyT0.

clone AT2 as MyA2 with 
  theory T1 <- MyT1.
(* fails with: module `T1.T0.M` is incompatible *)
```
However, this actually triggers the module is incompatible error rather than an anomaly. So there are very likely two issues. ^^

**Comment by strub** [comment]
@chdoc Could you check whether this is working on your big example?

**Pull request closed without merging**
