### PR TITLE
[internal] Removed `smart` constructors for various internal constructions.

### PR DESCRIPTION
**Pull request by Cameron-Low**

### CODE REVIEW

**Comment by strub** [comment]
Did you check that there is no regression in terms of checking time?

**Comment by fdupress** [comment]
Last run on `main` took 13 minutes. This one took 11 minutes.
Perhaps checking in a slightly more controlled environment would be good, but it seems OK at first glance.

**Comment by Cameron-Low** [comment]
I tracked a few runs of check on main and this branch. There's obviously a decent amount of variation but they both run in about 6:45 on my machine with the most recent check: main - 6:52, this - 6:36. So there's nothing noticeable on my end.

**Comment by strub** [comment]
Ok. This was a greedy optimization strategy that is useless. @bgregoir is the culprit for that, but unless he objects, we are good to go.

**Review by strub — APPROVED** [review]

**Pull request merged**
