### PR TITLE
Deploy oldlibs cleanup

### PR DESCRIPTION
**Pull request by Boutry**
This removes the dependency to the files in the oldlibs folder except for examples/to-port/PSS.ec and examples/old/list-ddh/list_ddh.ec due to the broken dependency to ISet.

### CODE REVIEW

**Comment by Boutry** [comment]
I will remove the oldlibs folder. That way people will not be tempted to rely on it now that it can be removed, at the exception of the two files still needing to be ported. I will also edit the changelog so that people can easily adapt their code if they were relying on oldlibs.

**Comment by strub** [comment]
Thank. You should also: 1. squash the PR, 2. rebase the PR on top of `main`.

**Comment by strub** [comment]
Is the PR ready to be reviewed?

**Comment by Boutry** [comment]
> Is the PR ready to be reviewed?

I would assume so. I will port the other two files sometimes later as it seems better to include what is already done asap. Also I did not edit the changelog as I did not find any. Is it normal?

**Pull request merged**
